"""empty message

Revision ID: 7608ee8c5faf
Revises: 4f081d24c42e
Create Date: 2026-08-03 14:23:42.754458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7608ee8c5faf'
down_revision = '4f081d24c42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_ingredient_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_constraint(batch_op.f('unique_recipe_ingredient'), type_='unique')
        batch_op.drop_constraint(batch_op.f('recipe_ingredients_ingredient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipe_ingredients_recipe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ingredients', ['ingredient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipe_ingredients_recipe_id_fkey'), 'recipes', ['recipe_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('recipe_ingredients_ingredient_id_fkey'), 'ingredients', ['ingredient_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('unique_recipe_ingredient'), ['recipe_id', 'ingredient_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
