"""add position to challenge rewards

Revision ID: de84c6b4d3cd
Revises: def58af9549c
Create Date: 2026-08-04 12:20:02.741767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de84c6b4d3cd'
down_revision = 'def58af9549c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_rewards', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
