"""add rules column to challenges

Revision ID: def58af9549c
Revises: 7608ee8c5faf
Create Date: 2026-08-04 10:31:14.975639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def58af9549c'
down_revision = '7608ee8c5faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_challenge_submissions_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_submissions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('rules')

    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_challenge_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###
